# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "isPro": true,
  "name": "Yarick2",
  "email": "torans2@overlook.net",
  "avatarUrl": "torrance.png",
  "password": "shining2"
}

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans2@overlook.net",
  "password": "shining2"
}

###

## Отправить изображение
POST http://localhost:5000/users/680633f18e07d14926cd807d/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< /jobs/six-cities(node)/markup/img/avatar-angelina.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Проверка статуса пользователя
## TODO: Почему Инвалид
GET http://localhost:5000/users/login/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuczJAb3Zlcmxvb2submV0IiwibmFtZSI6IllhcmljazIiLCJpZCI6IjY4MDYzM2YxOGUwN2QxNDkyNmNkODA3ZCIsImlhdCI6MTc0NTM4MDMxOCwiZXhwIjoxNzQ1NTUzMTE4fQ.JrSwwzEGXoDRmGm-7iTzUM5b-9TcR9J1qSZA1XajakM
###
