export const Path = {
  Create: '/',
  Update: '/:offerId',
  Delete: '/:offerId',
  Show: '/:offerId',
  Index: '/',
  Premium: '/premium/:city',
  Favorites: '/favorites',
  toggleFavorites: '/:offerId/favorites',
  Comments: '/:offerId/comments',
  Register: '/register',
  Login: '/login',
  Logout: '/logout',
  UserIdAvatar: '/:userId/avatar',
};
