# Оффер
## Получить список предложений по аренде
GET http://localhost:5000/offers HTTP/1.1
Content-Type: application/json

###

## Добавить новое предложение по аренде
POST http://localhost:5000/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuczJAb3Zlcmxvb2submV0IiwibmFtZSI6IllhcmljazIiLCJpZCI6IjY4MDYzM2YxOGUwN2QxNDkyNmNkODA3ZCIsImlhdCI6MTc0NTIzNjk4MiwiZXhwIjoxNzQ1NDA5NzgyfQ.-NzYtOtk_JXbQbRUymqzZOmqa8aFgqfqlOpOCvSzYSI

{
  "title": "Dream Home Awaits: Find Your Perfect House with Us",
  "description": "Embark on a journey to find your forever home with our collection of beautiful houses.",
  "city": "Amsterdam",
  "preview": "preview.jpg",
  "images": [
    "photo-1.jpg",
    "photo-2.jpg",
    "photo-3.jpg",
    "photo-4.jpg",
    "photo-5.jpg",
    "photo-6.jpg"
  ],
  "isPremium": true,
  "isFavorite": true,
  "type": "House",
  "bedrooms": 3,
  "maxAdults": 3,
  "price": 666,
  "comfort": [
    "Breakfast",
    "Air conditioning",
    "Laptop friendly workspace"
  ],
  "userId": "67b821a447c8fc70447fdf81",
  "rating": 5,
  "location": {
    "latitude": 52.370216,
    "longitude": 4.895168
  }
}

###

## Получение детальной информации по предложению

GET  http://localhost:5000/offers/6804b09a7839858bcb07c79b/ HTTP/1.1
Content-Type: application/json

###

## Удаление предложения

DELETE  http://localhost:5000/offers/67ee29d46798389c1e61b683/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuczJAb3Zlcmxvb2submV0IiwibmFtZSI6IllhcmljazIiLCJpZCI6IjY4MDYzM2YxOGUwN2QxNDkyNmNkODA3ZCIsImlhdCI6MTc0NTIzNjk4MiwiZXhwIjoxNzQ1NDA5NzgyfQ.-NzYtOtk_JXbQbRUymqzZOmqa8aFgqfqlOpOCvSzYSI

###

## Обновление предложения

PATCH  http://localhost:5000/offers/67ee29d46798389c1e61b683/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuczJAb3Zlcmxvb2submV0IiwibmFtZSI6IllhcmljazIiLCJpZCI6IjY4MDYzM2YxOGUwN2QxNDkyNmNkODA3ZCIsImlhdCI6MTc0NTIzNjk4MiwiZXhwIjoxNzQ1NDA5NzgyfQ.-NzYtOtk_JXbQbRUymqzZOmqa8aFgqfqlOpOCvSzYSI

{
  "title": "tes2t",
  "userId": "67b821a447c8fc70447fdf81"
}

###

## Получение списка премиальных предложений для города

GET  http://localhost:5000/offers/premium/amsterdam HTTP/1.1
Content-Type: application/json

###
